module.exports = {
  preset: 'react-native',
  setupFiles: ['./jest.setup.js'],
  rootDir: './',
  roots: ['<rootDir>/src', '<rootDir>/__tests__'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts'],
  coverageDirectory: 'coverage',
  testEnvironment: 'node',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/',
    '/__mocks__/',
    '/__fixtures__/',
    '/__generated__/',
    '(.*).d.ts',
    'src/index.tsx',
    'src/App.tsx',
    'src/theme.ts',
    'src/utils.ts',
    'src/translations.ts',
    'src/translations.tsx',
    'src/translations.js',
    'src/translations.jsx',
    'src/translations.json',
  ],
};
